name: Push to Azure Container Registry

on:
  push:
    branches:
      - release/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Extract version from branch name using sed
        run: |
          version=$(echo "${{ github.ref }}" | sed -E 's/^release\/(.*)$/\1/')
          echo "Extracted version: $version"

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          name: 'demoR'
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/AzureRegistryDemo.Backend
          file: ./src/AzureRegistryDemo.Backend/AzureRegistryDemo.Api/Dockerfile
          tags: ${{ secrets.AZURE_SUBSCRIPTION_ID }}/demoImage:$version
          push: true
