name: Push to Azure Container Registry and deploy to Azure Container App

on:
  pull_request:
    types: [closed]
    branches:
      - release/**

jobs:
 build-and-push-second:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Extract release version and Set to variable
        id: release_version
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -E 's/^refs\/heads\/release\/(.*)$/\1/')
          echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          creds: ${{ secrets.SP_CREDENTIALS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/TestProject/TestSolution
          file: ./src/TestProject/TestSolution/TestProject/Dockerfile
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/testimage:${{ env.IMAGE_VERSION }}
          push: true
